### ISSUE TITLE
有支持接收文件、图片、语音的计划吗？

### ISSUE THREAD

**Issue by mfyproject** [danni-cool/docker-wechatbot-webhook#10]
有支持接收文件、图片、语音的计划吗？

**Comment by danni-cool** [comment]
图片本身就是支持的，文件和语音wechaty支持的话，后面也会支持

**Comment by danni-cool** [comment]
## 消息推送
- [ ] 推送消息支持 URL
- [ ] 推送消息支持

## 消息接受
- [ ] 支持语音
- [ ] 支持文件
