### ISSUE TITLE
feautre 1.x -2.x discussion

### ISSUE THREAD

**Issue by danni-cool** [danni-cool/docker-wechatbot-webhook#11]
如果有好的建议欢迎评论或者提mr，以下是后续的研发计划
 
- windows版微信计划 #66
  
- <del>支持消息@ 人</del>(不可行）https://github.com/danni-cool/docker-wechatbot-webhook/issues/57

- [x] https://github.com/danni-cool/docker-wechatbot-webhook/issues/38
- [x] Discoard讨论频道 => [Discussion(Discord)](https://discord.gg/jRX5F2Km) 

- <del>已知长时间不主动发消息，最多在线 2 天，根据这个机制，定时向 文件传输助手 发消息，保持长时间在线的状态</del>（不可行）

- [x] **登出后的通知机制**
已知服务可能会因为微信的风控机制出现退登等情况，因此增加一套通知机制，支持在登出/首次登录时将登录二维码发送到指定的api。https://github.com/danni-cool/docker-wechatbot-webhook/issues/9

- [x] **消息Push**  https://github.com/danni-cool/docker-wechatbot-webhook/issues/6#issuecomment-1740181484
 - <del>发送URL卡片</del> (不支持 [ref](https://github.com/wechaty/puppet-wechat4u/blob/9e9f5ffc83808c0110b05ec58b5a6958ca68cbe7/src/puppet-wechat4u.ts#L831C4-L831C4))
 - <del>发送小程序</del>  (不支持 [ref](https://github.com/wechaty/puppet-wechat4u/blob/9e9f5ffc83808c0110b05ec58b5a6958ca68cbe7/src/puppet-wechat4u.ts#L839C17-L839C17))
 - <del>发送发送联系人卡片</del>  (不支持 [ref](https://github.com/wechaty/puppet-wechat4u/blob/9e9f5ffc83808c0110b05ec58b5a6958ca68cbe7/src/puppet-wechat4u.ts#L834C18-L834C40))
 - <del>发送位置</del> (不支持 [ref](https://github.com/wechaty/puppet-wechat4u/blob/9e9f5ffc83808c0110b05ec58b5a6958ca68cbe7/src/puppet-wechat4u.ts#L1166C18-L1166C38)
- <del>发送语音</del>(底层无此api支持)
- [x] 支持文件Url
- [x] 支持直接发文件

- [x] **消息 Receive** https://github.com/danni-cool/docker-wechatbot-webhook/issues/10 
  - [x] 支持 URL
  - [x] 支持语音
  - [x] 支持文件(包含图片）

- [x] 登录 api 优化
登录 api 原先是为了总是拿到最新的扫码 api 设计的，但是实际使用下来还得拿到数据判断后再拿到登录地址，其实可以简化一点。
  1. 登录成功返回 200 和登录人的信息
  2. 登出则直接 301 到扫码登录的 url

- [x] https://github.com/danni-cool/docker-wechatbot-webhook/issues/34

**Comment by jiyuhei** [comment]
除了国庆那时候刚刚用会频繁2天掉一次线，现在已经好几天了，都没掉线应该是网页登陆被信任了

**Comment by danni-cool** [comment]
> 除了国庆那时候刚刚用会频繁2天掉一次线，现在已经好几天了，都没掉线应该是网页登陆被信任了

get

**Comment by jiyuhei** [comment]
你这个docker 更新的话，是需要重新下载吗？有不删除的情况下直接更新的？我暂时稳定了，不想更新，触发有大版本更新我想问问是否支持类似这样的更新，免除配置重新修改，和环境的变更
docker-compose pull
docker-compose down
docker-compose up -d

**Comment by danni-cool** [comment]
> 你这个docker 更新的话，是需要重新下载吗？有不删除的情况下直接更新的？我暂时稳定了，不想更新，除非有大版本更新。我想问问是否支持类似这样的更新，免除配置重新修改，和环境的变更 docker-compose pull docker-compose down docker-compose up -d

可以的，image 指定  dannicool/docker-wechatbot-webhook:latest

**Comment by jiyuhei** [comment]
后期支持吗？还是现在就支持？

**Comment by danni-cool** [comment]
> 后期支持吗？还是现在就支持？

现在应该就OK的，每次拉的就是latest标签，你的 docker-compose 的image 不用指定标签就行了，你可以试一下

**Comment by ccliushou** [comment]
您好，非常感谢您的项目。我看了一下源码，有个疑惑（我是nodejs小白），我看到代码是这样：

第一个问题：
![image](https://github.com/danni-cool/docker-wechatbot-webhook/assets/10105646/6560a171-5b85-4442-b512-86624b067335)

这里的body是消息体吗？？我启动了我restfull服务，收不到这个消息。
![image](https://github.com/danni-cool/docker-wechatbot-webhook/assets/10105646/9ba02505-2843-4f62-a0ec-009b5c46f186)

![image](https://github.com/danni-cool/docker-wechatbot-webhook/assets/10105646/b456afe3-0793-4fd2-9f74-142d65bf46b4)


第二个问题：
我发送这个：
curl --location --request POST 'http://127.0.0.1:3001/webhook/msg' \
--header 'Content-Type: application/json'                          \
--data-raw '{"to": "文件传输助手","type": "text","content": "Hello World"}'

返回结果：
{"success":false,"message":"User is not found"}

截图如下：
![image](https://github.com/danni-cool/docker-wechatbot-webhook/assets/10105646/9e989c1e-cc45-45fd-90c1-abd561a7b13c)


不知道是什么原因。。

**Comment by danni-cool** [comment]
@ccliushou 看起来你的后端代码没有解析formData的流程，请求formData并不会带在body上，你可以打印完整请求体试试，另外可以 google 一下你的服务如何接收 formData，也许可以获得更多帮助。

你提供的curl我也没法执行成功,我试了下以下格式的是ok的

```bash
curl --location --request POST 'http://127.0.0.1:3001/webhook/msg' \
--header 'Content-Type: application/json' \
--data-raw '{
    "to": "文件传输助手",
    "type": "text",
    "content": "Hello World"
}'
```

**Comment by ccliushou** [comment]
我重新补充一下问题的描述，我单独提issue吧。

**Comment by jiyuhei** [comment]
上一次掉线的周期是1个星期左右，但是中间有好多次没有消息时间过长，现在我根据之前在项目中有一个人提了一个建议，我现在正在检测每小时发送一个随机的消息，看看是否在一个星期后会掉线，如果能撑过2个星期就说明，这个方法可行；如果不行我在尝试缩短到半小时测试一次，两个测试如果都效果或者没有效果，我都会及时反馈到这里。

**Comment by danni-cool** [comment]
@jiyuhei 优秀，我觉得一小时一次消息已经很极限了，3小时一发已经帮我度过了2天掉线期

**Comment by jiyuhei** [comment]
> @jiyuhei 优秀，我觉得一小时一次消息已经很极限了，3小时一发已经帮我度过了2天掉线期

我没有看到那个发送消息的建议，我就已经度过了2天掉线期了，我2天掉线一共发生3-5次，具体不记得了，然后就坚持了1一星期左右，然后就在11-12左右掉线了，现在我就测试一小时发送一次随机消息，现在已经坚持3天了，我看看后面是否能坚持2星期以上。

**Comment by jiyuhei** [comment]
> @jiyuhei，我觉得一小时一次优秀已经很极限了，3小时一发已经帮我度过了2天掉线期

好像不行哦，还是掉线呢，这个方法直接失效，没用

**Comment by jiyuhei** [comment]
> @jiyuhei，我觉得一小时一次优秀已经很极限了，3小时一次已经帮我度过了2天掉线期

![image](https://github.com/danni-cool/docker-wechatbot-webhook/assets/143597936/71ef1818-d636-427e-b421-3dc1e70d153f)
昨天晚上22:30后掉线的

**Comment by danni-cool** [comment]
@jiyuhei 其实核心问题还是uos不受信任的问题，和发消息还真无关

**Comment by jiyuhei** [comment]
> @jiyuhei其实核心问题还是不受信任的问题，并且发消息还真无关

到底是什么问题呢？掉线的时间，有时长有时短

**Comment by jiyuhei** [comment]
> > @jiyuhei，我觉得一小时一次优秀已经很极限了，3小时一次已经帮我度过了2天掉线期
> 
> 好像不行哦，还是掉线呢，这个方法直接失效，没用

还有其他方法吗？来实现机器人的方法

**Comment by danni-cool** [comment]
@jiyuhei 暂无，可能官方付费服务会好一点

**Comment by jiyuhei** [comment]
> @jiyuhei暂无，可能官方付费服务会好一点

哪一个官方付费呀？

**Comment by atorber** [comment]
非常棒的项目，我们正在修复puppet-xp在3.9.23版本下消息获取不到wxid的问题，届时将会获得更好的体验
我还没有实际运行你的这个项目，有个疑问请教一下，运行docker之后是有Windows的UI界面可以操作登录微信吗，因为puppet-xp目前并没有实现hook获取登录二维码的接口

**Comment by danni-cool** [comment]
> 非常棒的项目，我们正在修复puppet-xp在3.9.23版本下消息获取不到wxid的问题，届时将会获得更好的体验 我还没有实际运行你的这个项目，有个疑问请教一下，运行docker之后是有Windows的UI界面可以操作登录微信吗，因为puppet-xp目前并没有实现hook获取登录二维码的接口

感谢认可，运行后有一个 noVNC 的网页界面，运行在8080上，可以支持在浏览器里扫码登录, 参考自 https://github.com/chisbread/wechat-box

**Comment by 337076876** [comment]
能否实现艾特群里的某个人？

**Comment by danni-cool** [comment]
> 能否实现艾特群里的某个人？

可以，等下个版本
