### ISSUE TITLE
请求体

### ISSUE THREAD

**Issue by haypeng** [danni-cool/docker-wechatbot-webhook#14]
请问可以给一份有关于请求参数的例子吗？我目前的显示错误。
{
    "success": false,
    "message": "[to 的参数类型不是 string，type 的参数类型不是 string，content 的参数类型不是 string] params  is not valid, please checkout the api reference (https://github.com/danni-cool/docker-wechat-roomBot#body-%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E)"
}

**Comment by Simple4350** [comment]
{"isRoom":true,"to":"联大2021社招群","content":"测试消息","type":"text"}   呐，不知道你用什么post的 我curl 还有就是请求头要带个Content-type:application/json

**Comment by haypeng** [comment]
好的 谢谢  但是请问这个to里面只能是昵称吗？如果一个人的昵称是很奇怪的结构呢，例如甚至只是一个表情包应该如何 设置呢？

**Comment by Simple4350** [comment]
我还在研究 我试了一下 必须是昵称 备注不行

**Comment by haypeng** [comment]
好的  谢谢

**Comment by danni-cool** [comment]
> 好的 谢谢 但是请问这个to里面只能是昵称吗？如果一个人的昵称是很奇怪的结构呢，例如甚至只是一个表情包应该如何 设置呢？

to 直接复制文字表情试试

**Comment by danni-cool** [comment]
@haypeng  文档上已经补上 example https://github.com/danni-cool/docker-wechatbot-webhook#examplecurl
