### ISSUE TITLE
给微信发送消息问题

### ISSUE THREAD

**Issue by ccliushou** [danni-cool/docker-wechatbot-webhook#21]
我发送这个：
curl --location --request POST 'http://127.0.0.1:3001/webhook/msg'
--header 'Content-Type: application/json'
--data-raw '{"to": "文件传输助手","type": "text","content": "Hello World"}'

返回结果：
{"success":false,"message":"User is not found"}

截图如下：
![image](https://github.com/danni-cool/docker-wechatbot-webhook/assets/10105646/70e2347f-00c7-4657-bc5e-dc957f2979b0)

我看看也试试wsl。

**Comment by danni-cool** [comment]
已经解决，是windows bash 默认 gbk 编码导致服务端接收到的是乱码，添加charset utf8头都不行，要改系统设置
https://minsonlee.github.io/2020/11/how-to-set-utf8-with-git-bash

**Comment by ccliushou** [comment]
非常感谢。。ok了。。

**Comment by yzcheung** [comment]
![image](https://github.com/danni-cool/wechatbot-webhook/assets/33052368/2b6db653-d850-405a-ae51-008a8170cf78)
windows分支目前也存在这个问题

**Comment by danni-cool** [comment]
> ![image](https://private-user-images.githubusercontent.com/33052368/292788611-2b6db653-d850-405a-ae51-008a8170cf78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NjUwNzEsIm5iZiI6MTcwMzU2NDc3MSwicGF0aCI6Ii8zMzA1MjM2OC8yOTI3ODg2MTEtMmI2ZGI2NTMtZDg1MC00MDVhLWFlNTEtMDA4YTgxNzBjZjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA0MjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YmE5ZjQ5ZDEwZmMyZDgxNGUyZTQwM2NlNmQwNGU0ZWI0ODMwNmRiNTQ1NDM1MGU5NjA5ZDY3ZjIzNTE1MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-XELO9RFW6eLPmOQXL7rTKDdSzqhIF7-C0UJxsj7Zec) windows分支目前也存在这个问题，无法发送给文件传输助手

兄弟，你看下自己windows版本是不是通讯录里都没有文件传输助手这个联系人，估计被风控了

**Comment by yzcheung** [comment]
> > ![image](https://private-user-images.githubusercontent.com/33052368/292788611-2b6db653-d850-405a-ae51-008a8170cf78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NjUwNzEsIm5iZiI6MTcwMzU2NDc3MSwicGF0aCI6Ii8zMzA1MjM2OC8yOTI3ODg2MTEtMmI2ZGI2NTMtZDg1MC00MDVhLWFlNTEtMDA4YTgxNzBjZjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA0MjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YmE5ZjQ5ZDEwZmMyZDgxNGUyZTQwM2NlNmQwNGU0ZWI0ODMwNmRiNTQ1NDM1MGU5NjA5ZDY3ZjIzNTE1MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-XELO9RFW6eLPmOQXL7rTKDdSzqhIF7-C0UJxsj7Zec) windows分支目前也存在这个问题，无法发送给文件传输助手
> 
> 兄弟，你看下自己windows版本是不是通讯录里都没有文件传输助手这个联系人，我小号也有这个问题，估计被风控了

我重新检查了一下原来文件传输助手是需要手动点击添加为好友的，添加为好友以后就可以正常发送了。
![0B587985804647AE0B990319D11E3F04](https://github.com/danni-cool/wechatbot-webhook/assets/33052368/ef12c64d-6c9c-482d-ba12-21b5141f61f9)

**Comment by danni-cool** [comment]
@yzcheung interesting

**Comment by muzimu** [comment]
报错信息
{"success":false,"message":"Message sent failed","error":{"generatedMessage":true,"code":"ERR_ASSERTION","actual":-1,"expected":0,"operator":"==","response":{"status":200,"statusText":"OK","headers":{"connection":"close","content-type":"text/plain","strict-transport-security":"max-age=31536000","content-length":"77"},"config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":60000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","connection":"close","cookie":"pgv_pvi=9331003416690125000; pgv_si=s7059640748680588000; wxuin=2404336661; wxsid=ksPBjY1Juh2xNytV; wxloadtime=1704632202_expired; mm_lang=zh-CN; webwx_data_ticket=gSdYRvMWizKx+xdEXxfx2kTw; webwxuvid=26211c0a88afd34831a37376cdda1c41137a24a32dc89fcd18d7477ef94e7d587302240ba5d0feb5e415dcd775f4c1b4; webwx_auth_ticket=CIsBEKyM6rEFGoABOIHfDRDQxmvChNdMUkS6FScCei4a6LqaDWW9joPgBnM8c7BpFs4Z/HYVwFe5XjCva7FikTZH/G97594miHz1F/D0/dBq8S5EjYa5a9tYDml7yWpEUlqSWkGcsNT6jBN6a8XsVlYUZc3O16T/hifpnChmczV9pQ7fvt39kvCqeqU=; wxpluginkey=1704631201","Content-Length":"434","Accept-Encoding":"gzip, compress, deflate, br"},"Cookie":{"pgv_pvi":"9732234636685441000","pgv_si":"s2530149432410133000","wxuin":"2404336661","wxsid":"nxiOszTucoRHF/0O","wxloadtime":"1704631646_expired","mm_lang":"zh-CN","webwx_data_ticket":"gSfX1IAR2lNmcwcxW1SF+J8n","webwxuvid":"26211c0a88afd34831a37376cdda1c41137a24a32dc89fcd18d7477ef94e7d587302240ba5d0feb5e415dcd775f4c1b4","webwx_auth_ticket":"CIsBEJ6OntwLGoABGSkXPdsTvtvpwqee+wzHmycCei4a6LqaDWW9joPgBnM8c7BpFs4Z/HYVwFe5XjCva7FikTZH/G97594miHz1F/D0/dBq8S5EjYa5a9tYDml7yWpEUlqSWkGcsNT6jBN6a8XsVlYUZc3O16T/hifpnChmczV9pQ7fvt39kvCqeqU=","wxpluginkey":"1704631201"},"httpAgent":false,"httpsAgent":false,"method":"post","url":"https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxsendmsg","params":{"pass_ticket":"4qGyNbmZfNThIznp07MvEZ574CIr3khjsk%2FsOsa45GrDxyQII5skC%2ByX9C27OqIOXO6lX2V9ymwKKfRCEnkPOA%3D%3D","lang":"zh_CN"},"data":"{\"BaseRequest\":{\"Uin\":2404336661,\"Sid\":\"ksPBjY1Juh2xNytV\",\"Skey\":\"@crypt_6cbb61d4_aab15f85b37da7df71ffb355a4c847b0\",\"DeviceID\":\"e790558127618933\"},\"Scene\":0,\"Msg\":{\"Type\":1,\"Content\":\"Message sent successfully\",\"FromUserName\":\"@08d234ca1a96b74509c6844aa366c525e5f424ab8200d6122c925578b7f33693\",\"ToUserName\":\"@9c8960a1da1d4310655c45e6517348e0f00f4b346d5205ef576c380ffb3ce420\",\"LocalID\":1704632444512000,\"ClientMsgId\":1704632444512000}}"},"data":{"BaseResponse":{"Ret":-1,"ErrMsg":""},"MsgID":"","LocalID":""}},"tips":"发送文本信息失败"}}

**Comment by danni-cool** [comment]
@muzimu 你发给微信接口失败了，应该是登录掉了
