### ISSUE TITLE
探讨一下自动化的持久在线方式

### ISSUE THREAD

**Issue by ccliushou** [danni-cool/docker-wechatbot-webhook#22]
再次感谢作者的付出，这个项目是我见的的非常好的项目。。

如果想自动化的持久在线，想到两个办法：

一、是否可以定时（每小时）调用：
You can also check login by API: http://localhost:3001/loginCheck?token=XXXXXX

不知道这个方式中的接口有没有刷新在线状态的能力。还是说这个接口，就是获取当前状态，无法刷新当前状态。

二、本项目用两个微信启动两个实例，然后互相定时发消息？

**Comment by danni-cool** [comment]
@ccliushou 
1. 这个接口在登录时返回登录的用户，不登录返回登录二维码，只是能拿到扫码url，扫码这个环节还是得用手机，所以不是定时调用的问题

2. 这个感觉ban得更快，流程长，不太通用

**Comment by danni-cool** [comment]
2. 也许作为使用方，你可以写个定时服务，每隔3小时给文件传输助手发个消息之类的，等待你的反馈

**Comment by ccliushou** [comment]
嗯。第二个方式，我想了一下，刚才说复杂了。能否：就一个微信，启动一个本项目的实例，然后定时的给：文件传输助手发信息呢？

**Comment by ccliushou** [comment]
@danni-cool 哈哈，想一起去了。。我先试试这个方式。看看效果吧。再次感谢。

**Comment by PeterChen1997** [comment]
之前用 wechaty 经常会自动掉线，目前应该是微信策略放松了一些，基本上一天都能在了🤣 但是开发微信真的太封闭了，开发起来太累🤣

**Comment by danni-cool** [comment]
@PeterChen1997 不发任何消息，两天掉一次吧大概

**Comment by PeterChen1997** [comment]
> @PeterChen1997 不发任何消息，两天掉一次吧大概

如果发的话是时间会更长一些吗🤔

**Comment by danni-cool** [comment]
> > @PeterChen1997 不发任何消息，两天掉一次吧大概
> 
> 如果发的话是时间会更长一些吗🤔

正在佛系测试这个方案，明天看看还在不在线

**Comment by PeterChen1997** [comment]
> > > @PeterChen1997 不发任何消息，两天掉一次吧大概
> > 
> > 
> > 如果发的话是时间会更长一些吗🤔
> 
> 正在佛系测试这个方案，明天看看还在不在线

我记得之前有持久化登录状态的方案，现在每次都要重新登录，不知道怎么实现的hhh

**Comment by danni-cool** [comment]
@PeterChen1997 哦？那可以找找，昨天半夜里掉了，今天试试隔一段时间推消息的方案

**Comment by PeterChen1997** [comment]
不行，重试了三四次

**Comment by PeterChen1997** [comment]
难顶 恢复了，估计给封了 4h 2333

**Comment by danni-cool** [comment]
> 难顶 恢复了，估计给封了 4h 2333

干坏事了吧 [滑稽脸]

**Comment by PeterChen1997** [comment]
> > 难顶 恢复了，估计给封了 4h 2333
> 
> 干坏事了吧 [滑稽脸]

啥也没干，中间也没什么消息，这个风控策略搞不懂🤔

**Comment by jiyuhei** [comment]
我国庆后上班到现在了，一个星期终于在昨天掉线了，昨天看到这个方案今天我已经重启服务了，定时一个小时发一次消息到群里，然后测试后期是否会掉线。

**Comment by jiyuhei** [comment]
我已经在测试，如果这个方法有用有结果，我及时在这里反馈，我会根据掉线的情况及时调整消息发送时间。

**Comment by danni-cool** [comment]
> 我已经在测试，如果这个方法有用有结果，我及时在这里反馈，我会根据掉线的情况及时调整消息发送时间。

11

**Comment by keyborad-man** [comment]
> 我已经在测试，如果这个方法有用有结果，我及时在这里反馈，我会根据掉线的情况及时调整消息发送时间。

个人有个小建议：不要定时发送消息，可以加个随机时间，发送的内容也随机一下这样风控的概率应该会小一点

**Comment by lHackl-007** [comment]
> > 我已经在测试，如果这个方法有用有结果，我及时在这里反馈，我会根据掉线的情况及时调整消息发送时间。
> 
> 个人有个小建议：不要定时发送消息，可以加个随机时间，发送的内容也随机一下这样风控的概率应该会小一点

我定时是为了测试好找到掉线的时间节点，我现在测试的方案是一小时发送一次消息，发送的内容我固定几套词语随机发送的，这样，在哪个时间节点掉线了，我这边可以瞬间找到，然后好给作者反馈顺便优化。我用的是几年的老微信，自己的小号，还没被封过。

**Comment by lHackl-007** [comment]
我12-13号开始测试的，暂时未掉线

**Comment by jiyuhei** [comment]
> > 我已经在测试了，如果这个方法有用有结果，我会及时反馈，我会根据掉线的情况及时调整消息发送时间。
> 
> 个人有个小建议：不要定时发送消息，可以加个随机时间，发送的内容也随机一下这样风控的概率应该会小一点
我定时是为了测试好找到掉线的时间节点，我现在测试的方案是一小时发送一次消息，发送的内容我固定几套词语随机发送的，这样，在哪个时间节点掉线了，我这边可以瞬间找到，然后好给作者反馈顺便优化。我用的是几年的老微信，自己的小号，暂时还没出现被封过的迹象。

**Comment by jiyuhei** [comment]
我12-13号开始测试的，暂时未掉线

**Comment by danni-cool** [comment]
> 我12-13号开始测试的，暂时未掉线

我3小时一个随机消息，也还稳定，2天没掉，再观察一段时间，ok的话集成到启动服务器里去

**Comment by Daydaylw3** [comment]
> 凉了，被关小黑屋了
>
> AssertionError: 1205 == 0

这个错误码就是被关小黑屋了吗？`AssertionError: 1205 == 0

**Comment by techctu** [comment]
> 2. 也许作为使用方，你可以写个定时服务，每隔3小时给文件传输助手发个消息之类的，等待你的反馈

我在某个地方看到过，之前有做这类方案的，特别容易被封。

**Comment by danni-cool** [comment]
@techctu
是的，比如我的一个号，web版的文件助手直接无了

**Comment by techctu** [comment]
> @techctu 是的，比如我的一个号，web版的文件助手直接无了

这个项目非常 nice，我也在跟收图崩溃的问题。

**Comment by danni-cool** [comment]
> > @techctu 是的，比如我的一个号，web版的文件助手直接无了
> 
> 这个项目非常 nice，我也在跟收图崩溃的问题。

感谢认可，windows分支后面会尝试用hook的方式，puppet-xp 问题比较多，有兴趣可以去discord讨论

**Comment by EashShow** [comment]
AssertionError [ERR_ASSERTION]: 1101 == 0

我今天遇到了这个错误，扫码登录后，没过几秒钟，就会自动下线。
重启Docker，然后发现好了。

不知道这个是什么类型的错误，如何规避？谢谢！

另外，用这种方式操作微信，如果收发微信消息本身是合法的，会不会被禁啥的？会不会被腾讯定义为外挂？

**Comment by danni-cool** [comment]
@EashShow https://github.com/danni-cool/wechatbot-webhook/issues/188#issuecomment-2014715100，希望多提供一些上下文，是否是外挂自己把握
