### ISSUE TITLE
探讨一下重启服务无需登录的可能性

### ISSUE THREAD

**Issue by PeterChen1997** [danni-cool/docker-wechatbot-webhook#37]
我记得之前是用了一个wechat-gpt 的服务，可以把登录状态储存起来，然后重启服务不用再次扫码来着，但是想不起来了🤣

我用的 zeabur，经常会出现容器调度重启容器的情况，导致还得扫码🤣

**Comment by PeterChen1997** [comment]
老哥，感觉可以搞一个 tg 组或者 discord，可以聊聊天还

**Comment by danni-cool** [comment]
wechaty 有断线重连机制，wechat-gpt我晚上研究下

**Comment by PeterChen1997** [comment]
赞👍

**Comment by rangdengdashi** [comment]
我看[Wechaty](https://github.com/wechaty/wechaty)现在是用的UOS桌面版的请求头，现在还有几率过几天登录掉吗？

**Comment by danni-cool** [comment]
@rangdengdashi 两天一掉，但是定时给发消息可以不掉，目前有两个小伙伴在测试这个方案 #11

**Comment by lHackl-007** [comment]
> Referen

有一个问题，扫描二维码的时候，始终都要信任等待，正常的电脑登录几次后，就信任该设备了，这个要是解决了，应该也会减少掉线把

**Comment by danni-cool** [comment]
@lHackl-007 目测不是发消息的问题，已经测试几轮了，还是uos不被信任的问题，一般这个是可以到手机微信自己选自动登录信任的，网页版是没这个选项的，后面可能考虑使用 wine + windows版微信 + dll注入的方案替换底层客户端

**Comment by jiyuhei** [comment]
> @lHackl-007已经测试了几轮了，不是发消息的问题，，还是网页微信不被信任的问题，一般客户端登录是可以到手机微信自己选自动登录信任的，网页版是没有这个选项的，后面可以考虑使用 linux + wine + windows 版微信 + dll注入的方案替换简单客户端解决这个问题

我还在测试，现在我让手机微信一直在线，看看是否会掉线。你新方案可以尝试一下。

**Comment by danni-cool** [comment]
> 老哥，感觉可以搞一个 tg 组或者 discord，可以聊聊天还
@jiyuhei @PeterChen1997 
Discord频道

https://discord.gg/jRX5F2Km

**Comment by qotu99** [comment]
> wechaty 有断线重连机制，wechat-gpt我晚上研究下，群晚点搞

我用chatgpt-on-wechat的确可以不断线，但是wechatbot-webhook这个晚上半夜都会掉，要是能不掉线就好了。

**Comment by danni-cool** [comment]
> > wechaty 有断线重连机制，wechat-gpt我晚上研究下，群晚点搞
> 
> 我用chatgpt-on-wechat的确可以不断线，但是wechatbot-webhook这个晚上半夜都会掉，要是能不掉线就好了。

这样的吗，晚点我研究下

**Comment by danni-cool** [comment]
@qotu99 用的python Itchat hack成了uos桌面客户端，我研究一下

**Comment by danni-cool** [comment]
写了个demo，基于chatgpt-on-wechat 的 itchat，欢迎测试 https://github.com/danni-cool/itchat-demo

**Comment by qotu99** [comment]
> 写了个demo，基于chatgpt-on-wechat 的 itchat，欢迎测试 https://github.com/danni-cool/itchat-demo

我找时间测试一下。ps：chatgpt-on-wechat 从上次回复你也一直在测试，一直运行的很稳定，一直没掉线。估计你这个有戏。

**Comment by danni-cool** [comment]
> 这个demo主要是看会不会被T下线吗？

用了chatgpt-on-wechat 核心itchat逻辑，不确定会不会掉线，希望帮忙测试下给到反馈

**Comment by hsmamw** [comment]
> > 这个demo主要是看会不会被T下线吗？
> 
> 用了chatgpt-on-wechat 核心itchat逻辑，不确定会不会掉线，希望帮忙测试下给到反馈

好的。我用虚拟机部署下。帮你测一下。

**Comment by hsmamw** [comment]
这个登录有点奇怪呀。我重启了虚拟机。重新运行python3 main.py.直接不用扫码。直接处理登录好的状态了。 @danni-cool

**Comment by danni-cool** [comment]
> 这个登录有点奇怪呀。我重启了虚拟机。重新运行python3 main.py.直接不用扫码。直接处理登录好的状态了。 @danni-cool

热重载机制免登，和当前项目是一样的，也有实现该机制，在缓存生效期间不需要扫码

**Comment by qotu99** [comment]
已连续运行 24小时+ 一直没断线，自动回复有效，先报告一下，继续测试。

**Comment by danni-cool** [comment]
> 已连续运行 24小时+ 一直没断线，自动回复有效，先报告一下，继续测试。

我好像快连续运行两天了

**Comment by danni-cool** [comment]
2天半掉了，可能是因为在新环境登陆，切换了本地ip继续运行试试

**Comment by hsmamw** [comment]
昨天下午重启过虚拟机。 目前到现在没掉过线。

**Comment by qotu99** [comment]
> 2天半掉了，可能是因为在新环境登陆，切换了本地ip继续运行试试

我下午也掉了，同时运行的 chatgpt-on-wechat 也掉了，这两个项目后台运行的进程都没有了。我之前运行一个类似项目(名字忘记了)掉了后，进程都还在，只是需要重新登录，这次有点奇怪。

**Comment by gaoyaqiu** [comment]
用 wechatbot-webhook 几乎每天都会掉线，人都麻了。 我本来还以为可能是长时间没有推送消息导致超时断开了，然后设置了1分钟推一次作为心跳检测，还是会掉线。。。大概每天早上8点左右的样子掉。

**Comment by danni-cool** [comment]
@gaoyaqiu web协议就是这样，等等这个项目吧，有不错的进展 https://github.com/danni-cool/wechatbotKit-py-http

**Comment by hsmamw** [comment]
继周日重启到今天下午，也掉线了。

**Comment by gaoyaqiu** [comment]
看了下[WeChatFerry](https://github.com/lich0821/WeChatFerry) 这个库，需要一台 Windows 服务器挂着微信才能用。

**Comment by gaoyaqiu** [comment]
> 看了下[WeChatFerry](https://github.com/lich0821/WeChatFerry) 这个库，需要一台 Windows 服务器挂着微信才能用。

没有大佬这个[wechatbot-webhook](https://github.com/danni-cool/wechatbot-webhook)用起来方便，就掉线这个不稳定，我现在又3天没掉线了，但有时又1天掉一次。

**Comment by danni-cool** [comment]
@gaoyaqiu 不要作死，一分钟发一条，容易被限制，基于wechatFerry底层的服务封装已经在写了，应该没啥难度，就是时间问题了。

**Comment by hsmamw** [comment]
> > 已连续运行 24小时+ 一直没断线，自动回复有效，先报告一下，继续测试。
> 
> 我好像快连续运行两天了，已经在用itchat重构了，会写python的来一起搞 https://github.com/danni-cool/wechatbotKit-py-http

能搞个支持wcfhttp的吗？ 想用http 和nodered 做交互。 tcp不知道怎么弄，发送和接收
