### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by XHHzZz** [danni-cool/docker-wechatbot-webhook#39]
我新注册一个微信号登录报错 信息：{"event":"error","error":{"code":2,"details":"AssertionError [ERR_ASSERTION]: 1 == 0\n    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)\n    at /app/node_modules/wechat4u/lib/core.js:227:24\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"1 == 0","name":"AssertionError","stack":"AssertionError [ERR_ASSERTION]: 1 == 0\n    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)\n    at /app/node_modules/wechat4u/lib/core.js:227:24\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"user":null} 这个是为什么？

**Comment by danni-cool** [comment]
新号，实名+绑定手机号+绑定银行卡三连

**Comment by jiyuhei** [comment]
还有就是确认你的新微信是否支持微信官方的web登陆。

**Comment by danni-cool** [comment]
项目的uos协议认证了基本都行，尽管我两个号都登不上web 微信

**Comment by jiyuhei** [comment]
> 项目的uos协议认证了基本都行，虽然我两个号都登不上web微信

你说官方收费的是哪个呀，能告诉我吗？我去看看

**Comment by danni-cool** [comment]
> > 项目的uos协议认证了基本都行，虽然我两个号都登不上web微信
> 
> 你说官方收费的是哪个呀，能告诉我吗？我去看看

https://github.com/wechaty/puppet-supports

**Comment by dgo2dance** [comment]
> https://github.com/wechaty/puppet-supports

微信之前可以登录web版  今天就提示  为了保障你的账号安全,暂不支持使用网页版微信；  这种的有办法解决吗

**Comment by danni-cool** [comment]
> > https://github.com/wechaty/puppet-supports
> 
> 微信之前可以登录web版 今天就提示 为了保障你的账号安全,暂不支持使用网页版微信； 这种的有办法解决吗

如果不是因为自己发送信息之类违规，可能等几个小时就能登陆了
