### ISSUE TITLE
如何自定义端口啊

### ISSUE THREAD

**Issue by lucasjinreal** [danni-cool/docker-wechatbot-webhook#52]
参考了这个教程：https://sspai.com/post/83274

docker run -d --name wcbot -p 3001:3001 dannicool/docker-wechatbot-webhook

我发现即便是更改 -p 3003:3003 还是会监听3001端口，但是我的服务有一个重要的进程已经使用了该端口，应如何十号

**Comment by danni-cool** [comment]
> 参考了这个教程：https://sspai.com/post/83274
> 
> docker run -d --name wcbot -p 3001:3001 dannicool/docker-wechatbot-webhook
> 
> 我发现即便是更改 -p 3003:3003 还是会监听3001端口，但是我的服务有一个重要的进程已经使用了该端口，应如何十号


```
docker run -d --name wcbot -p 3003:3001 dannicool/docker-wechatbot-webhook
```
-p 3003:3001: 这个参数设置了端口映射。它告诉 Docker 将主机的 3003 端口映射到容器的 3001 端口。这意味着如果你在浏览器中访问主机的 3003 端口，它实际上会访问到容器中运行的服务的 3001 端口。
