### ISSUE TITLE
如何在接受消息回调的时候返回数据直接回复消息发送方？

### ISSUE THREAD

**Issue by lucasjinreal** [danni-cool/docker-wechatbot-webhook#53]
设置reciveMsgUrl回调， 看起来目前只是单向的，如果我要接收消息回复，就还是得走发送消息的接口。但目前问题是，我只想用一个远程服务器设置一个接受消息的回调，然后再我本地的windows上面启动docker （反过来的）

这样的话，虽然远程服务器可以处理接收消息，但是发送就没法发送了。

然而理论上来说，是不是可以我本地启动的docker，访问了接收消息的回调服务，那为什么不把接受消息服务的返回值，用来返回呢？这样对我这个需求，就不用两台服务器了 （PS：我的接受消息服务器需要跑大模型，不太适合阿里云）, 只用一台服务器，至少本地测试方便很多。

**Comment by lucasjinreal** [comment]
[eval]:1
RECVD_MSG_API=http://127.0.0.1:3002
                  ^

SyntaxError: Unexpected token ':'
    at new Script (node:vm:94:7)
    at createScript (node:vm:251:10)
    at Object.runInThisContext (node:vm:299:10)
    at node:internal/process/execution:82:21
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:81:62)
    at evalScript (node:internal/process/execution:103:10)
    at node:internal/main/eval_string:29:3

**Comment by danni-cool** [comment]
> 设置reciveMsgUrl回调， 看起来目前只是单向的，如果我要接收消息回复，就还是得走发送消息的接口

1. 消息的收发一定是单向的，**因为 docker-wechatbot-webhook 的定位是一个供外部集成的 http 服务**，但如果说想用一个服务去解决收发问题，当然也是可以的，这可能需要稍微懂一些 `node.js` 的知识，直接fork项目在需要上报报的地方自己去实现对应的功能

> 我只想用一个远程服务器设置一个接受消息的回调，然后再我本地的windows上面启动docker （反过来的）

2. 用一个远程服务器去解决接受消息的回调，目前项目是支持的，但我好奇的是在 windows 上启动docker，要如何告诉你的远程服务器需要回复的消息？这个逻辑没有太明白，也许画一个图会有助于理解？

> 是不是可以我本地启动的docker，访问了接收消息的回调服务，那为什么不把接受消息服务的返回值，用来返回呢？

3. 接受消息的返回值，是返回的，利用了外部 revcvd_msg_api 承接了，既然返回内容需要承接载体，不通过http 接口的形式，有什么更好的暴露接口的建议可以供参考呢？也许就像我第1点描述的，你需要一个可以自己编程的快速接入服务而不是一个收发消息需要额外自己处理的 wechat as a http service， 如果是这样的情况，重头构建一个 wechaty 的应用可能更加合适

**Comment by lucasjinreal** [comment]
@danni-cool 2. 就是我本地启动docker，收消息服务在远程服务器。可以做到吗？

**Comment by danni-cool** [comment]
1. 对于生产环境来说：收消息本身就是可以在外部处理，所以“收消息服务在远程服务器”没毛病。
2. 当你 docker 服务部署在本地作为实际收发消息的服务，就得解决本地和远程服务通信的问题，这应该是是你的核心痛点。
3. 相对简单比较常规做法是两套服务部署在一起（我也是这么做的）

**Comment by lucasjinreal** [comment]
@danni-cool  自己这么弄没问题，我的需求会复杂一些，我的收消息服务器是远程的，但是可能5-6个人会在本地，他们可能没有服务器，我想实现他们用我的远程来回复消息。

事实上这应该可以作为一个可选项，虽然接和推可以分开，但是接受本身是一个post，那么他理论上应该可以收到一个返回，然后返回发不发就可以取决于用户怎么启动docker（例如设置一个标志位

**Comment by danni-cool** [comment]
1. 对于消息接受：我可以在收消息时增加当前用户标志位（比如哪个微信）之类的，因为你需要区分收到了哪个人的消息。
2. 对于回复有一些问题：
  - 现有处理收消息服务端和本地多示例之间需要处理通信问题
  - 据我所知 post 没有这样的能力去处理收发，tcp 在发送完数据就已经断开了
 
可能你需要一个websock，你的收消息服务端可以控制所有客户端的收发对吧？

**Comment by lucasjinreal** [comment]
不是的，我理解是现在的设计是收到消息然后调用远程处理接口回调，但是这个回调只是给远程消息了，但是远程处理完了怎么回这个逻辑是没有的，我是i想把远程处理消息变成一个可以公用的逻辑，i.e. 接入某个大模型，他不管谁发来的，就是把收到的消息处理一道，然后post return给请求方，请求方再决定这个处理过的response是回复还是不处理。

**Comment by danni-cool** [comment]
> 不是的，我理解是现在的设计是收到消息然后调用远程处理接口回调，但是这个回调只是给远程消息了，但是远程处理完了怎么回这个逻辑是没有的，我是i想把远程处理消息变成一个可以公用的逻辑，i.e. 接入某个大模型，他不管谁发来的，就是把收到的消息处理一道，然后post return给请求方，请求方再决定这个处理过的response是回复还是不处理。 因为请求方是登录方，回的权限自然是在于他，而服务端就是一个处理的逻辑，他虽然也可以回，但他不能给其他local端发消息，但是收到消息返回给post调用方的时候，是可以及时让调用方来回复的

可以基于当前docker再构建一层你的客户端业务逻辑

**Comment by danni-cool** [comment]
@lucasjinreal done了，更新2.5.0 配合文档食用
