### ISSUE TITLE
RECVD_MSG_API=https://127.0.0.1:3002                    ^  SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by lucasjinreal** [danni-cool/docker-wechatbot-webhook#55]
Windows 设置本地代理

RECVD_MSG_API=https://127.0.0.1:3002
                   ^

SyntaxError: Unexpected token ':'

```
docker run -d --name wcbot -p 3001:3001 dannicool/docker-wechatbot-webhook -e RECVD_MSG_API="https://127.0.0.1:3002"
```

**Comment by danni-cool** [comment]
docker run -d --name wcbot -p 3001:3001 -e RECVD_MSG_API="https://127.0.0.1:3002"  dannicool/docker-wechatbot-webhook
