### ISSUE TITLE
接受服务端fastapi如何构建传入数据结构

### ISSUE THREAD

**Issue by lucasjinreal** [danni-cool/docker-wechatbot-webhook#56]
Hello, 我用这么个写法，但是由于传进来的数据string 和 binary共用，传入的结构解析失败

```
@app.post("/wc_receive")
def handle_wcbot_msg_receive_callback(type: str = Form(...),
                                      content: UploadFile = File(...),
                                      source: str = Form(...),
                                      isMentioned: Optional[str] = Form(None),
                                      isSystemEvent: Optional[str] = Form(None)):
```

```
INFO:     119.7.10.198:7242 - "POST /wc_receive HTTP/1.1" 422 Unprocessable Entity
INFO:     117.10.198:7243 - "POST /wc_receive HTTP/1.1" 422 Unprocessable Entity
```

咋整

**Comment by danni-cool** [comment]
先判断type，再条件化解析content

**Comment by lucasjinreal** [comment]
@danni-cool thank u, 已解决。

那个post的想法，其实就是想实现这么一个功能：

```
@app.post("/wc_receive")
def handle_wcbot_msg_receive_callback(type: str = Form(...),
                                      ...
                                      isSystemEvent: Optional[str] = Form(None)):
    if type == 'text':
        # send msg from http://localhost:3001/webhook/msg
        room = source['room']
        from_part = source['from']
        print(source)
        if room != "":
            print('msg from room: ', room['payload']['topic'])
        else:
            from_name = from_part['payload']['name']
            print('msg from: ', from_name)
        print(content)
        # get id and resend

        rsp = llm(content)
        return {"text": rsp}
```

在这里return  一个回复，有办法可以实现吗？

**Comment by danni-cool** [comment]
不能，独立于不同网段的http服务，用python也没法实现这个功能吧，你这种适合组装功能在一起

**Comment by lucasjinreal** [comment]
不是，我的意思是不是客户端post的这个请求吗？ 为什么不能把post的返回利用起来呢

**Comment by danni-cool** [comment]
重点不是post返回，你返回也要服务接，阿里云的服务 + 本地的docker服务，两者怎么通信？

**Comment by lucasjinreal** [comment]
客户端不是本身就可以提供http访问推送消息吗？ 那我理解客户端应该具备给某个用户发消息的能力，直接把post的返回推送给发送方，就实现了回复拦截、处理、再回应的功能.

不然的话，就必须得两台服务

**Comment by danni-cool** [comment]
这些都可以实现实现，只是这样的业务很重，拦截处理再回应，这种更像sdk该干的活。

我的服务走 http 接口，本身就是为了把繁琐的服务独立于这个收发体系之外，就像微信只是个工具，你的大脑去想要发什么。

如果既不想直接改代码，又要做拦截器、自定义回复，又要考虑不同语言之间兼容性你会如何设计？

**Comment by lucasjinreal** [comment]
我看了一下，eatapple的那个wechat sdk golang的似乎更好一点，自由度高

**Comment by danni-cool** [comment]
> 我看了一下，eatapple的那个wechat sdk golang的似乎更好一点，自由度高

你的需求要的是一个SDK

**Comment by danni-cool** [comment]
> 客户端不是本身就可以提供http访问推送消息吗？ 那我理解客户端应该具备给某个用户发消息的能力，直接把post的返回推送给发送方，就实现了回复拦截、处理、再回应的功能.
> 
> 不然的话，就必须得两台服务

@lucasjinreal 今天又考虑了下这个问题，确实post请求利用起来，就只要一台公网的ip服务器，最近正在实现这点

**Comment by lucasjinreal** [comment]
对的，其实这是双向回路的一个特例：当且仅当及时回复的场景适用，例如聊天AI。
实现好了叫我

**Comment by danni-cool** [comment]
> 对的，其实这是双向回路的一个特例：当且仅当及时回复的场景适用，例如聊天AI。 实现好了叫我

ok，碰巧在实现好友邀请时考虑到这个问题，但是如果大量slave机器post请求到你服务器，是不是得考虑并发问题

**Comment by lucasjinreal** [comment]
我以前考虑的是给用户用，但是这得让服务器登录许多个微信，感觉不太现实，如果只是我的微信，那就只是回复艾特我的消息了。
考虑到微信的频率限制，这个频次应该不会太高
