### ISSUE TITLE
能否实现艾特群里的某个人？

### ISSUE THREAD

**Issue by danni-cool** [danni-cool/docker-wechatbot-webhook#57]
能否实现艾特群里的某个人？

_Originally posted by @337076876 in https://github.com/danni-cool/docker-wechatbot-webhook/issues/11#issuecomment-1809394262_

**Comment by danni-cool** [comment]
@337076876 网页协议不支持@人，无解

**Comment by mingyuz00** [comment]
aaa @张三 aaaaa 复制 除 a字母的保函看起来像空格的字符一起发送文本消息即可@人
