### ISSUE TITLE
每几天会掉线一次，再登录有时会报 AssertionError: 1205 == 0     有共同问题和解决方法的吗

### ISSUE THREAD

**Issue by dgo2dance** [danni-cool/docker-wechatbot-webhook#59]
每几天会掉线一次，再登录有时会报 AssertionError: 1205 == 0     有共同问题和解决方法的吗

**Comment by pkptzx** [comment]
当再登录后,会报,但好像不是所有的都爆.大部分都会爆.
WARN Room find() got more than one(2) result

**Comment by danni-cool** [comment]
无解决办法，请关注windows分支进度
