### ISSUE TITLE
如何配合n8n推送消息

### ISSUE THREAD

**Issue by jiyuhei** [danni-cool/docker-wechatbot-webhook#6]
我想推送语雀更新的消息，然后推送到微信上，但是我配置不出来，能否提供一下n8n的流程图，谢谢大佬

**Comment by danni-cool** [comment]
1. 在 n8n 工作流（workflows）中建立一条工作流
2. 工作流的起始节点选择 `on webhook call`
    2.1 HTTP Method 选择 `POST`
    2.2 将该节点的 webhook Test URLs 拷贝到 `语雀 -> 你的知识库管理 -> Webhook地址 -> 勾选你需要触发的推送 -> 点击添加推送`，此时增加了一条 n8n 的 webhook 地址
    2.3 回到 n8n, 在 Webhook 节点开启 `Listen For Test Event`，开始侦听语雀知识库的推送
    2.4 再语雀你刚新增 webhook 的地方点击测试，确认 webhook 的连通性
    2.5 不出意外的话，在n8n节点上就能收到一条数据

结构大概如下
```json

[
  {
    "headers": {
      "x-real-ip": "192.168.1.1",
      "host": "example.url:888",
      "x-forwarded-for": "192.168.1.1",
      "connection": "upgrade",
      "content-length": "154",
      "content-type": "application/json",
      "sofa-traceid": "ac136ax216951253845388971130",
      "sofa-rpcid": "0.1",
      "user-agent": "node-urllib/2.41.0 Node.js/16.20.2 (Linux 3.10; x64)"
    },
    "params": {},
    "query": {},
    "body": {
      "msgtype": "markdown",
      "markdown": {
        "title": "语雀测试消息",
        "text": "\n#### 这是一段测试内容\n**webhook 名称**: n8n语雀-微信工作流\n"
      }
    }
  }
]
```
3. 回到n8n，再新建两个节点对数据进行组装和推送，分别是 Code 节点 和 Http Request节点

整个流程是 语雀配置webhook -> n8n配置节点和组装数据（webhook call 节点 -> code 节点 -> http request 节点）

4. 确保整个流程通了，把 webhook 节点 test url 换成 production url，需要在语雀重新配置一遍

**Comment by danni-cool** [comment]
语雀推文应该是url 卡片，目前还不支持，可以给我提mr，后面可以支持

**Comment by danni-cool** [comment]
@wxyShine 感谢认可

wechaty相关后续计划：
1. 推送这块wechaty几种类型会补全
2. 增加收消息的钩子 (已完成还未上线）text and img
3. 补全wechaty 相关通知事件触发收消息钩子

**Comment by jiyuhei** [comment]
感谢，后面我用其他第三方的推送集成商解决了，自己把推送的流程也编写好了，还有一个问题就是微信好像会掉线，这个是否有方法解决，让他保持在线

**Comment by jiyuhei** [comment]
> 语雀推文到微信你可能想要 url 卡片，目前还不支持，可以给我提 issue，后面会支持
