### ISSUE TITLE
接入zapier的可能性？

### ISSUE THREAD

**Issue by huanzh1** [danni-cool/docker-wechatbot-webhook#63]
Danni你好，在少数派上看到了这个项目。好奇是否有可能把这个bot接入zapier，这样就可以把微信对话框里的内容与腾讯会议、outlook calendar、备忘录、文件管理之间打通了，我不太懂技术但觉得这个会很cool

**Comment by danni-cool** [comment]
面对诸多的自动化工具 maker、n8n、ifftt 还有你提到的 zapier，如何让每个应用都可以接入是个问题。如果单独去开发一个定制的系统，就要开发n多定制，比较浪费时间。http 协议的 docker-wechatbot-webhook 提供了对接上述所有自动化系统的可能性，可能需要一些编程思维
