### ISSUE TITLE
发送的文件含有中文名称,微信收到的文件会乱码

### ISSUE THREAD

**Issue by XHHzZz** [danni-cool/docker-wechatbot-webhook#71]
![image](https://github.com/danni-cool/docker-wechatbot-webhook/assets/120640558/35548f5e-3910-4d81-9c71-7992f508a33e)
![image](https://github.com/danni-cool/docker-wechatbot-webhook/assets/120640558/5e8368e1-2c33-4e3a-9448-cebb69f44269)

这里进行了两次测试   英文没得问题，但是中文会乱码，
请问 大佬这个可以解决嘛？

**Comment by Pai-Po** [comment]
修复代码我放下面了，还得需要作者重新打包下镜像；
@XHHzZz @danni-cool 

diff --git a/src/route/msg.js b/src/route/msg.js
index a162de2..6e38d62 100644
--- a/src/route/msg.js
+++ b/src/route/msg.js
@@ -1,7 +1,6 @@
 const Service = require('../service')
 const Middleware = require('../middleware')
 const Utils = require('../utils/index')
-const iconv = require('iconv-lite')
 
 module.exports = function registerPushHook({ app, bot }) {
   // 处理 POST 请求
@@ -16,15 +15,7 @@ module.exports = function registerPushHook({ app, bot }) {
       if (req.is('multipart/form-data')) {
         to = req.body.to
         isRoom = req.body.isRoom || '0'
-        content =
-          req.files.find((item) => {
-            // 使用iconv-lite来解码文件名
-            item.originalname = iconv.decode(
-              Buffer.from(item.originalname, 'binary'),
-              'utf8',
-            )
-            return item.fieldname === 'content'
-          }) || {}
+        content = req.files.find((item) => item.fieldname === 'content') || {}
         type = 'file'

**Comment by danni-cool** [comment]
@Pai-Po 更进一步，提个pr吧！
