### ISSUE TITLE
接收微信消息要怎么配置呀，能不能出个示例，谢谢了~

### ISSUE THREAD

**Issue by lcg2016** [danni-cool/docker-wechatbot-webhook#76]
如题

**Comment by XHHzZz** [comment]
docker run -d \
--name wxBotWebhook \
-p 9999:9999\
-e RECVD_MSG_API="http://192.168.110.110:9998/get/msg" \
-e LOGIN_API_TOKEN=token\
-v /etc/localtime:/etc/localtime:ro \
dannicool/docker-wechatbot-webhook:latest



RECVD_MSG_API  这个就是接收小心的API 
参数类型为form

**Comment by danni-cool** [comment]
正在重写收消息的文档，@XHHzZz 的例子还ok，就是需要懂点后端知识

**Comment by AnRan-727** [comment]
![image](https://github.com/danni-cool/wechatbot-webhook/assets/48827004/b459f8b8-53fe-4fae-97eb-e82bfaa6f4a8)
配置了接收消息的api了   为什么会报错这个呀

**Comment by AnRan-727** [comment]
我的这个接口是没问题的，可以接收到请求的
![image](https://github.com/danni-cool/wechatbot-webhook/assets/48827004/a9d1183f-4f89-422f-a49f-d61b2954265a)

**Comment by AnRan-727** [comment]
我测试了别的请求  是可以请求到的
![image](https://github.com/danni-cool/wechatbot-webhook/assets/48827004/d340f13e-85d4-44e1-8fe3-d89946a0a97d)

**Comment by AnRan-727** [comment]
> 你的消息转发到了容器内部的 `localhost:7560`，而不是宿主机的 `localhost:7560`，你需要将 `RECVD_MSG_API` 参数改成 Docker 宿主机的 IP

这样吗  我查询出来的宿主机IP是这个
![image](https://github.com/danni-cool/wechatbot-webhook/assets/48827004/e4df7e64-b7bb-4d19-9a46-ac76cf348e1e)

![image](https://github.com/danni-cool/wechatbot-webhook/assets/48827004/d78b5ebc-7a8b-4047-b3f7-edca486fcf55)

**Comment by AnRan-727** [comment]
> 你的消息转发到了容器内部的 `localhost:7560`，而不是宿主机的 `localhost:7560`，你需要将 `RECVD_MSG_API` 参数改成 Docker 宿主机的 IP

好的，明白了，已解决！谢谢！！！太感谢了！！！！！！！！！！！！！！！

**Comment by AnRan-727** [comment]
可是现在我又有个问题了，我发消息通过curl发不了了  这是为什么呢  提示未授权  但是我用的token是正确的token呀 @Cassius0924

**Comment by AnRan-727** [comment]
> 看看`curl`命令和报错👀

诶呀  解决了解决了   我设置了LOGIN_API_TOKEN
但是用设置后的token也不行   然后我把LOGIN_API_TOKEN删掉了  就可以了
