### ISSUE TITLE
为了保障你的账号安全，暂不支持使用网页版微信。

### ISSUE THREAD

**Issue by glwhappen** [danni-cool/docker-wechatbot-webhook#84]
![image](https://github.com/danni-cool/docker-wechatbot-webhook/assets/40719048/dad21792-5a55-4f00-afa6-436114a31ff6)

这样是不是这个账号没办法使用

**Comment by danni-cool** [comment]
https://github.com/leochen-g/wechrome 可以用这个项目插件在网页使用
