### ISSUE TITLE
发消息是发生错误

### ISSUE THREAD

**Issue by glwhappen** [danni-cool/docker-wechatbot-webhook#85]
wxBotWebhook  | 15:47:39 WARN Contact find() got more than 1 result: 2 total
wxBotWebhook  | Error handling request: AssertionError [ERR_ASSERTION]: -1 == 0
wxBotWebhook  |     at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)
wxBotWebhook  |     at /app/node_modules/wechat4u/lib/core.js:537:24
wxBotWebhook  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
wxBotWebhook  |     at async PuppetWechat4u.messageSendText (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:640:9)
wxBotWebhook  |     at async WechatifiedUserClass.say (/app/node_modules/wechaty/dist/cjs/src/user-modules/contact.js:300:23)
wxBotWebhook  |     at async Object.formatAndSendMsg (/app/src/service/msg.js:8:7)
wxBotWebhook  |     at async /app/src/route/msg.js:123:28 {
wxBotWebhook  |   generatedMessage: true,
wxBotWebhook  |   code: 'ERR_ASSERTION',
wxBotWebhook  |   actual: -1,
wxBotWebhook  |   expected: 0,
wxBotWebhook  |   operator: '==',
wxBotWebhook  |   response: [Object],
wxBotWebhook  |   tips: '发送文本信息失败'
wxBotWebhook  | }

**Comment by danni-cool** [comment]
duplicate issue, see #60
