### ISSUE TITLE
新加的好友获取不到名称

### ISSUE THREAD

**Issue by glwhappen** [danni-cool/docker-wechatbot-webhook#87]
{"room":"","to":{"_events":{},"_eventsCount":0,"id":"@cfb64364352740190bf822275fad2012effc08049d2c1db88056a83c57494ea3","payload":{"alias":"","avatar":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=1644152229&username=@cfb64364352740190bf822275fad2012effc08049d2c1db88056a83c57494ea3&skey=@crypt_3e633608_8a76f6305d59c0b0cbd6cfce27e54da6","friend":false,"id":"@cfb64364352740190bf822275fad2012effc08049d2c1db88056a83c57494ea3","name":"笔记","phone":[],"star":false,"type":1}},"from":{"_events":{},"_eventsCount":0,"id":"@6c9cd9b3ea40ae53d6ab996e6b270ba87acae2dccd23413293adfabfd74bcaf0","payload":{"address":"","alias":"","avatar":"","city":"","friend":false,"gender":0,"id":"@6c9cd9b3ea40ae53d6ab996e6b270ba87acae2dccd23413293adfabfd74bcaf0","name":"","phone":[],"province":"","signature":"","star":false,"weixin":"","type":1}}}

新加的好友，获取的name信息为空

**Comment by danni-cool** [comment]
https://github.com/danni-cool/docker-wechatbot-webhook/issues/72
