### ISSUE TITLE
wechat4u库更新

### ISSUE THREAD

**Issue by rcy1314** [danni-cool/docker-wechatbot-webhook#90]
如果你的Docker日志里出现了`Error: 连续3次同步失败，5s后尝试重启\n at /app/node_modules/wechat4u/lib/wechat.js:129:22"}`这样的报错，根据报错堆栈信息，错误发生在wechat4u库的wechat.js文件的第129行，具体是在同步失败后触发的重启逻辑，更新命令：`npm update wechat4u
`或`yarn upgrade wechat4u`但更新的要求是Node.js版本是"^18.17.0 || >=20.5.0"，如果你的系统版本不允许安装高版本Node则可以直接在package.json文件底部更改wechat4u版本号为1.14.12
![we](https://jsd.onmicrosoft.cn/gh/rcy1314/tuchuang@main/uPic/we.jpg)
然后构建你的docker容器如 `docker build -t wxbot .` 然后再docker run -d你的容器即可，已测试，之后不会再报此类错误

**Comment by danni-cool** [comment]
感谢反馈，yarn安装后 lock 文件已经是1.14.12了，稍后更新
